app/models.py
from datetime import datetime
from . import db 
from . import login_manager
from flask_login import UserMixin,AnonymousUserMixin
from sqlalchemy import desc
from werkzeug.security import generate_password_hash, check_password_hash


@login_manager.user_loader
def load_user(userid):
    return User.query.get(int(userid))



tags = db.Table('bookmark_tag',
    db.Column('tag_id',db.Integer,db.ForeignKey('tag.id')),
    db.Column('bookmark_id',db.Integer,db.ForeignKey('bookmark.id'))
)

class Bookmark(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    url = db.Column(db.Text, nullable=False)
    date = db.Column(db.DateTime, default=datetime.utcnow)
    description = db.Column(db.String(300))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    _tags = db.relationship('Tag', secondary=tags, backref=db.backref('bookmarks', lazy='dynamic'))




    @staticmethod
    def newest(num):
        return Bookmark.query.order_by(desc(Bookmark.date)).limit(num)

    @property
    def tags(self):
        return ",".join([t.name for t in self._tags])

    @tags.setter
    def tags(self, string):
        if string:
            self._tags = [Tag.get_or_create(name) for name in string.split(',')]

    def __repr__(self):
     return "<Bookmark '{}' : '{}'>".format(self.description, self.url)


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True)
    email = db.Column(db.String(120), unique=True)
    bookmarks = db.relationship('Bookmark', backref='user', lazy='dynamic')
    password_hash = db.Column(db.String)
    

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password) 

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)        

    @staticmethod
    def get_by_username(username):
        return User.query.filter_by(username=username).first()
  
    def __repr__(self):
        return "<User '{}'>".format(self.username)
        
class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(25), nullable=False, unique=True, index=True)

    @staticmethod
    def get_or_create(name):
        try:
            return Tag.query.filter_by(name=name).one()
        except:
            return Tag(name=name)
    @staticmethod
    def all():
        return Tag.query.all()

          

    def __repr__(self):
        return self.name

app/bookmark/forms.py
from flask_wtf import Form
from wtforms.fields import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired,url,Length, Email, Regexp, EqualTo
from wtforms import ValidationError
from wtforms.fields.html5 import URLField

from ..models import User

class BookmarkForm(Form):
    url = URLField('Enter your url:', validators=[DataRequired(), url()])
    description = StringField('Enter Description:' )
    tags = StringField('Tags', validators=[Regexp(r'^[a-zA-Z0-9, ]*$', message=
    'Tags can only contain letters and numbers')])
    submit = SubmitField('Save')


    def validate(self):
        if not self.url.data.startswith("http://") or\
            self.url.data.startswith("https://"):
            self.url.data = "" + self.url.data

        if not Form.validate(self):
            return False
        if not self.description.data:
            self.description.data = self.url.data
        
        stripped = [t.strip() for t in self.tags.data.split(',')]
        not_empty = [tag for tag in stripped if tag]
        tagset = set(not_empty)
        self.tags.data = ",".join(tagset)

        return True

app/__init__.py
import os
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_moment import Moment
from config import config
# from models import User, Bookmark,Tag



moment = Moment()
db = SQLAlchemy()
bootstrap = Bootstrap()
# bootstrap.init_app(app)

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
# login_manager.init_app(app)



def create_app(config_name):
    app = Flask(__name__) 
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    

    bootstrap.init_app(app)
    db.init_app(app)
    moment.init_app(app)
    login_manager.init_app(app)


    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    from .bookmark import bookmark as bookmark_blueprint
    app.register_blueprint(bookmark_blueprint, url_prefix='/bookmark')

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    @app.errorhandler(404)
    def page_not_found(e):
        return render_template('404.html'),404


    @app.errorhandler(500)
    def server_error(e):
        return render_template('500.html'),500

 

    return app
    # import models
    # import ..views

app/bookmark/__init__.py
from flask import Blueprint

bookmark = Blueprint('bookmark', __name__)

from . import views
from ..models import Tag

@bookmark.app_context_processor
def inject_tags():
    return dict(all_tags=Tag.all)

app/bookmark/views.py
from flask import Flask, render_template,url_for,request,redirect,url_for,flash,abort
from flask_login import login_required,login_user, logout_user, current_user
from . import bookmark
from forms import BookmarkForm
from ..models import User, Bookmark,Tag
from ..import db
from .. import models



@bookmark.route('/add', methods=['GET', 'POST'])
@login_required
def add():
    form = BookmarkForm()
    if form.validate_on_submit():
        url = form.url.data
        description = form.description.data
        tags = form.tags.data
        bm = Bookmark(user=current_user,url=url, description=description, tags=tags)
        db.session.add(bm)
        db.session.commit()
        flash("Stored  '{}'".format(description))
        return redirect(url_for('main.index'))
    return render_template('add.html', form=form)




@bookmark.route('/edit/<int:bookmark_id>', methods=['GET','POST'])
@login_required
def edit_bookmark(bookmark_id):
    bookmark = Bookmark.query.get_or_404(bookmark_id)
    if current_user != bookmark.user:
        abort(403)
    form = BookmarkForm(obj=bookmark)
    if form.validate_on_submit():
        form.populate_obj(bookmark)
        db.session.commit()
        flash('Your bookmark was saved succesfully')
        return redirect(url_for('main.user', username=current_user.username))
    return render_template('bookmark_form.html',form=form, title='Edit Bookmark')


@bookmark.route('/delete/<int:bookmark_id>', methods=['GET','POST'])
@login_required
def delete_bookmark(bookmark_id):
    bookmark = Bookmark.query.get_or_404(bookmark_id)
    if current_user != bookmark.user:
        abort(403)
    if request.method == "POST":
        db.session.delete(bookmark)
        db.session.commit()
        flash( 'Deleted successfully')
        return redirect(url_for('main.user', username=current_user.username))
    else: 
        flash( 'Please confirm delete ')
    return render_template('confirm_delete.html',bookmark=bookmark, nolinks=True)

@bookmark.route('/tag/<name>')
@login_required
def tag(name):
    tag = Tag.query.filter_by(name=name).first_or_404()
    return render_template('tag.html', tag=tag)

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from flask import render_template, flash, redirect, request, url_for
from flask_login import login_user, logout_user, login_required, current_user
from . import main
from .. import db,login_manager
from ..models import Bookmark,User, Tag


 


@main.route('/')
@main.route('/home')
def home():
    return render_template('base.html', new_bookmarks=Bookmark.newest(5))    


@main.route('/index')
@login_required
def index():
    return render_template('index.html', new_bookmarks=Bookmark.newest(5))



@main.route('/user/<username>')
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template('user.html',user=user)    

app/templates/add.html
{% extends "base.html" %}
<!--{% import "bootstrap/wtf.html" as wtf %}-->
{% block title %}
My Bookmark | Log in
{% endblock %}

{% block content %}
            
              
<div class="row">
              <div class="col s12 m12 l6 offset-l3">
                <div class="card-panel hoverable">
                  <h4 class="header2 center-align">Add url</h4>
                  <div class="row">
                   <form method="post" class="form" role="form" id='SignForm'>
                        {{ form.hidden_tag() }}
                      <div class="row">
                        <div class="input-field col s12">
                         <i class="material-icons prefix">link</i>
                           <input type="text" class="validate" id="url" name="url" placeholder="Start with http://">
                          <label for="url">Enter your url</label>
                        </div>
                      </div>
                      <div class="row">
                        <div class="input-field col s12">
                          <i class="material-icons prefix">description</i>
                         <input type="text" class="validate" id="description" name="description" placeholder="Enter description">
                          <label for="description">Description</label>
                        </div>
                      </div>  
                      <div class="row">
                        <div class="input-field col s12">
                          <i class="material-icons prefix">loyalty</i>
         <input type="text" class="validate" id="tags" name="tags" placeholder="seperate tags with commas">
          <label for="tags">Tags</label>
                      </div>

                        <div class="row">
                          <div class="input-field col s12">
                            <button class="btn red waves-effect waves-light left" type="submit">Submit
                              <i class="material-icons left">send</i>
                            </button>
                    
                          </div>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
</div>

{% endblock %}
{% block sidebar %}
{% endblock %}
 {% block parallax %}
 {% endblock %}

app/templates/base.html
  <!DOCTYPE html>
  <html>
    <head>
      <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet"> 
      <!--Import materialize.css-->
      <!--<link type="text/css" rel="stylesheet" href= '{{ url_for('static', filename='materialize.css')}}'>-->
      <link type="text/css" rel="stylesheet" href= '{{ url_for('static', filename='animate.min.css')}}'>
       <!-- Compiled and minified CSS -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">
      <link rel="stylesheet" href= '{{ url_for('static', filename='main2.css')}}'>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
     <!--<link type="text/css" rel="stylesheet" href="css/main.css"/>-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <!--<script type="text/javascript" src="../static/js/materialize.min.js"><-->
  
      <!-- to Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
<header>
    <body>
        <div class="header-container">
      
<!-- Dropdown Structure -->

<ul id="dropdown1" class="dropdown-content">
  <li><a href="#!">My Profile</a></li>
  <li><a href="#!">Change password</a></li>
  <li class="divider"></li>
  <li><a href="{{ url_for('auth.logout')}}">Logout</a></li>
</ul>
 <!--<div class="navbar-fixed">-->
<nav>
  <div class="nav-wrapper">
    
    {% if current_user.is_authenticated %} <a href="{{url_for('main.index')}}" class="brand-logo"> 
      {% else %}<a href="{{url_for('main.home')}}" class="brand-logo"> {% endif %}
      <i class="tiny material-icons left">turned_in</i>Booky+</a>
	  <!--menu button-->
     <a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
        <li><a href="{{url_for('bookmark.add')}}"><i class="material-icons left">add</i>Add url</a></li>
        {% if current_user.is_authenticated%}
        <li><a href="{{ url_for('main.user', username=current_user.username) }}"><i class="material-icons left">view_list</i>View Bookmarks</a></li>
        <li><a href="badges.html"><i class="material-icons left">search</i></a></li>
        {% else %}
         <li><a class="waves-effect waves-light btn" href="{{url_for('auth.signup')}}"><i class="material-icons left">person_add</i>Get Started</a></li>
      <!--<li><a href="{{url_for('auth.signup')}}"><i class="material-icons left">person_add</i>Get Started</a></li>-->
       {% endif %}
      <!-- Dropdown Trigger -->
      {% if current_user.is_authenticated%}
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><i class="material-icons right">more_vert</i></a></li>
      {% else %}
       <li><a href="{{url_for('auth.login')}}"><i class="material-icons left">input</i>Log In</a></li>
        {% endif %}
    </ul>
    <!--side nav view-->
	{% if current_user.is_authenticated%}
<ul class="side-nav fixed" id="slide-out">
<style>
	header,
	main,
	wrapper,
	footer {
		padding-left: 300px;
	}
	
	@media only screen and (max-width: 992px) {
		header,
		main,
		footer {
			padding-left: 0;
		}
	}
</style>
		{% else %}
		<ul class="side-nav" id="slide-out">
			{% endif %}
          <li><div class="userView">
    <!--side view background-->
      <div class="background">  
        <img src="../static/bg.jpg">
      </div>
      <a href="#!user"><img class="circle" src="../static/face2.jpg"></a>
      <!--Side menu for authenticated users-->
      {% if current_user.is_authenticated%}
      <a href="#!name"><span class="white-text name">{{ current_user.username|capitalize }}</span></a>
      <a href="#!email"><span class="white-text email">{{ current_user.email | capitalize}}</span></a>
      {% else %}
      <a href="#!name"><h3><span class="white-text name">Hi,Stranger!</h3></span></a>
      {% endif %}
    </div></li>
    <!--end of authentication-->
<!--side menu action-->
<li><a class="subheader">Get Started</a></li>
 <li><a href="{{url_for('bookmark.add')}}"><i class="material-icons left">add</i>Add url</a></li>
        {% if current_user.is_authenticated%}
        <li><a href="{{ url_for('main.user', username=current_user.username) }}"><i class="material-icons left">view_list</i>View Bookmarks</a></li>
        <li><a href="badges.html"><i class="material-icons left">search</i>search</a></li>
	    <li><div class="divider"></div></li>
		<li><a class="subheader">My Account</a></li>
	   
		<li><a href="{{ url_for('auth.change_username')}}"><i class="material-icons left">person</i>Change username</a>
		<li><a href="{{ url_for('auth.change_password')}}"><i class="material-icons left">lock_open</i>Change password</a>
        <li><a href="{{ url_for('auth.logout')}}"><i class="material-icons left">keyboard_tab</i>Logout</a></li>
			 <li><a href="{{url_for('auth.login')}}"><i class="material-icons left">share</i>Share Booky+</a></li>
			 <li><a href="{{url_for('auth.login')}}"><i class="material-icons left">help</i>Stuck?</a></li>
        {% else %}
		    <!--nav bar menu for non and auth users-->
         <li><a href="{{url_for('auth.signup')}}"><i class="material-icons left">person_add</i>Get Started</a></li>
     <li><a href="{{url_for('auth.login')}}"><i class="material-icons left">input</i>Log In</a></li>
	 <li><a href="{{url_for('auth.login')}}"><i class="material-icons left">help</i>Stuck?</a></li>
       {% endif %}</li>
    </ul>
  </div>
</nav>
 </div>
 <!--End of nav bar-->
 <!--start: Fab button for non and auth users-->
   <div class="fixed-action-btn">
    <a class="btn-floating btn-large blue">
      <i class="large material-icons">edit</i>
    </a>
    <ul>
      
   
      {% if current_user.is_authenticated%}
      <li><a class="btn-floating red" href="{{url_for('main.index')}}"><i  class="material-icons">home</i></a></li>
      <li><a class="btn-floating yellow darken-1"href="{{url_for('auth.logout')}}"><i class="material-icons">keyboard_tab</i></a></li>
      <li><a class="btn-floating green"href="{{ url_for('main.user', username=current_user.username) }}"><i class="material-icons">library_books</i></a></li>
      {% else %}
       <li><a class="btn-floating red" href="{{url_for('main.home')}}"><i  class="material-icons">home</i></a></li>
       <li><a class="btn-floating yellow darken-1"href="{{url_for('auth.login')}}"><i class="material-icons">input</i></a></li>
       <li><a class="btn-floating green"href="{{url_for('auth.signup')}}"><i class="material-icons">person_add</i></a></li>
        {% endif %}
      <li><a class="btn-floating blue" href="{{url_for('bookmark.add')}}"><i class="material-icons">library_add</i></a></li>
    </ul>
  </div>
<!--End: FAB button-->
<!--Start: Home parallax image-->
{% block parallax %}
  <div class="parallax-container">
            <div class="caption">
            <h1 class="animated fadeInLeftBig">Welcome to <span>Booky+</span></h1>
            <p class="animated fadeInRightBig">Store - Share - Available - Fast</p>
            <a data-scroll class="btn btn-start animated fadeInUpBig" href="{{url_for('auth.signup')}}">Join now</a>
          </div>
               
               <a id="tohash" href="#intro"><i class="fa fa-angle-down"></i></a>
    <div class="parallax"><img src="../static/bg.jpg"></div>
  </div>
  
  
  <div class="section white">
    <div class="container">
    <div class="row">
      <div class="added">
        <!--about bookyplus-->
        <h3 id='intro'class="center-align">Meet your new Bookmark App</h3>
      <p class="grey-text text-darken-3 lighten-3">Store and share all your favorite Bookmarks in one place.You can also view what's new at a glance and visit and browse through tags.</p>
    </div>
  </div>
  </div>
  </div>
  
  <!--/End (paralax)-->
{% endblock %}


<div class="main-container">
            <div class="main wrapper clearfix">

                 <div class="row">
                   <!--alert,error flash messages-->
                <article class="col s12 m12 l6 offset-l3 flash">
                    {% with messages = get_flashed_messages() %}
                    {% if messages %}
                    <ul>
                       {% for message in messages %}
                        <li class="center-align"> {{ message}}</li>
                  <!--<a  class='btn' onhover=Materialize.toast('{{ message}}!', 4000) </a>-->
        
                        {% endfor %}
                    </ul> 
                    {% endif %}  
                    {% endwith %}
                </article>
                
                 </div>

                 {% block content %}
                {% endblock %}
 <!--tags for auth users-->
  {% block sidebar %}
{% if current_user.is_authenticated%}
                      <aside style="margin-top: 60px;">
                      <h3><i class="fa fa-tags" aria-hidden="true"></i> Tags</h3>
                     {% for t in all_tags() %}

                     <a href= "{{  url_for('bookmark.tag', name=t)}}">{{ t }}</a>

                     {% endfor %}
                </aside>
                {%else%}
				            </div> 
                </div> 
  <!--<div class="parallax-container">
    <div class="parallax"><img src="../static/6.png"></div>
  </div>-->
  <div class="section white">
    <div class="row container">
      <div class='added'>
      <h3 class="header center-align">Online Bookmarks</h3>
      <p class="grey-text text-darken-3 lighten-3">Organize your online bookmarks in nested cards and tags, search for tags, or view for your last added bookmark.</p>
      </div>
    </div>
  </div>
    <div class="parallax-container">
    <div class="parallax"><img src="../static/6.png"></div>
  </div>

{% endif %}
                {% endblock  %}


<!-- #main -->
        <!--</div>  #main-container -->
        </header>
        <footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">I am Social!</h5>
                <div id="social-box">
        <div class="inner text-center">
            <a target="_blank" href="http://github.com/jimmykimani" class="fa fa-github"></a>
            <a target="_blank" href="http://twitter.com/jimkaks" class="fa fa-twitter"></a>
            <a target="_blank" href="http://medium.com/@jimmykimani" class="fa fa-medium"></a>
            <a target="_blank" href="http://medium.com/@jimmykimani" class="fa fa-github-alt "></a>
        </div>
    </div>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Add url</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">View Bookmarks</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Tags</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Logout</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
<h3 class="footer-title center-align">All rights reserved made with <i class="fa fa-heart-o"> </i>  by Jimmy kimani | 2017</h3>
            </div>
          </div>
        </footer>
 <script>
  $('.button-collapse').sideNav({
    menuWidth: 300, // Default is 300
    edge: 'left', // Choose the horizontal origin
    closeOnClick: true, // Closes side-nav on <a> clicks, useful for Angular/Meteor
    draggable: true // Choose whether you can drag to open on touch screens
  });
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>
      <script src= '{{ url_for('static', filename='main.js')}}'></script>
      <script src= '{{ url_for('static', filename='materialize.js')}}'></script>


      
    </body>
  </html>

app/templates/bookmark.html
    </ul>
    <ul class="bookmarks">
        {% for bookmark in bookmarks %}
        <li>

            {% include 'bookmark_list.html' %}
        </li>

{% endfor %}

    </ul>

app/templates/bookmark_form.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}
My Bookmark | {{ title }}
{% endblock %}

{% block content %}

     {{form.hidden_tag()}}
    <h3> <i class="fa fa-pencil" aria-hidden="true"></i>   {{ title }} 
</h3>
    <div class="col s12 m12 l6 offset-l3" method='post'>
    {{ wtf.quick_form(form) }}
</div>
       
   

{%endblock%}
{% block sidebar%}
{%endblock%}
 {% block parallax %}
 {% endblock %}

app/templates/bookmark_list.html
       <div class="row">
        <div class="col s12 m12 l12">
  <!--<div class="card">
      <div class="card-stacked">-->
          <div class="card-panel hoverable animated fadeIn">
<ul class='bookmarks card-content'>
    {% for bookmark in bookmarks %} 

    <li>
        <a class='header' href="{{ bookmark.url}}" target="_blank">
            <h3 class="description">
                <i class="material-icons left">label_outline</i>
                {{ bookmark.description|truncate(50, killwords=True) }}
                </h3>
                <span class='url fa fa-link'> </i>
                    {{ bookmark.url|truncate(25, killwords=True) }}
                 </span>   
                     </a>
                <div class='info'>
                    <span class="tags fa fa-tags">
                        {% if bookmark.tags %}
                        {% for t in bookmark._tags %}
                            <a href="{{ url_for('bookmark.tag', name=t)}}">{{ t }}</a>
                            {% endfor %}
                        {% else %} No tags.
                        {% endif %}
                    </span>
                    <br>
                    Added by <a href="{{ url_for('main.user', username=bookmark.user.username) }}">
                    {{ bookmark.user.username}}
                    </a> <i class="fa fa-clock-o" aria-hidden="true"></i>
                    {{ moment(bookmark.date).fromNow() }}.
                    {% if current_user == bookmark.user%}
                    <span class='editlinks'>
                        <a href="{{ url_for('bookmark.edit_bookmark',bookmark_id=bookmark.id) }}"><i class="material-icons left">mode_edit</i>
                        <a href="{{ url_for('bookmark.delete_bookmark',bookmark_id=bookmark.id) }}">  <i class="material-icons left">delete</i>
                    </span>
                    {% endif %}



                </div>
    </li>
    {% endfor %}

app/templates/change_password.html
{% extends "base.html" %}
<!--{% import "bootstrap/wtf.html" as wtf %}-->
{% block title %}
My Bookmark | Log in
{% endblock %}

{% block content %}
            
              
<div class="row">
    <div class="col s12 m12 l6 offset-l3">
        <div class="card-panel hoverable">
            <h4 class="header2 center-align">Change Password</h4>
            <div class="row">
                <form method="post" class="form right-alert" role="form" id='SignForm'>
                    {{ form.hidden_tag() }}
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="material-icons prefix">lock</i>
                            <input type="password" class="validate" id="old_password" name="old_password" placeholder="Old Password">
                            <label for="old_password">Old Password</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="material-icons prefix">lock</i>
                            <input type="password" class="validate" id="password" name="password" placeholder="Password">
                            <label for="password">Password</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="material-icons prefix">lock</i>
                            <input type="password" class="validate" id="password2" name="password2" placeholder="Confirm password">
                            <label for="password2">Confirm password</label>
                        </div>                  
                        <div class="row">
                            <div class="input-field col s12">
                                <button class="btn red waves-effect waves-light left" type="submit">Update Password
                              <i class="material-icons left">lock_open</i>
                              
                            </button>
                            </div>
                        </div>
                    <!--</div>-->
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block sidebar %}
{% endblock %}
 {% block parallax %}
 {% endblock %}            

app/templates/change_username.html
{% extends "base.html" %}
<!--{% import "bootstrap/wtf.html" as wtf %}-->
{% block title %}
My Bookmark | Log in
{% endblock %}

{% block content %}
            
              
<div class="row">
  <div class="col s12 m12 l6 offset-l3">
    <div class="card-panel hoverable">
      <h4 class="header2 center-align">Change Username</h4>
      <div class="row">
        <form method="post" class="form right-alert" role="form" id='SignForm'>
          {{ form.hidden_tag() }}
          <div class="row">
            <div class="input-field right-alert col s12">
              <i class="material-icons prefix">account_circle</i>
              <input type="text" class="validate" id="username" name="username" placeholder="New Username">
              <label for="username" data-error="wrong" data-success='good'>New Username</label>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s12">
              <i class="material-icons prefix">lock</i>
              <input type="password" class="validate" id="password" name="password" placeholder="Password">
              <label for="password">Password</label>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <button class="btn red waves-effect waves-light left" type="submit">Change username
                              <i class="material-icons left">lock_open</i>
                              
                            </button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}
{% block sidebar %}
{% endblock %}
 {% block parallax %}
 {% endblock %}

app/templates/confirm_delete.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}
My Bookmark |Delete bookmark
{% endblock %}

{% block content %}
<section>
    <h1><i class="fa fa-trash"></i> Delete Bookmark </h1>
    {% include 'bookmark.html'%}

    <form action '' method='post'>
        <span style='color:red'>Are you sure you want to delete this bookmark?</span>
        <br><br>
        <a href="{{ url_for('main.user', username=current_user.username) }}">
            <button type='button'> No,take me out of here</button>
            </a>
            <button type='submit'> yes please!</button>
            </form>
</section>
{%endblock%}
{% block sidebar%}
{% endblock %}
 {% block parallax %}
 {% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% block title %}
My Bookmark | Welcome
{% endblock%}
{% block content %}
               <article>
                   
                      {% if current_user.is_authenticated %} <h1 class="left-align animated fadeInDown"><i class="fa fa-user"> </i> Welcome, {{ current_user.username|capitalize }}!
                     
                      {% else %}<h1 class="service-title text-center"> Not a member yet?  <a class='service-title'href="{{ url_for('auth.signup') }}">Join now!</h1> {% endif %}</a></h1>
                      
                       
                    
                    <section>
                        <!--<h1 class="service-title text-center" >Recently Added</h1>-->
                        {% if new_bookmarks.count() > 0 %}
                            {% with bookmarks=new_bookmarks %}
                                {% include 'bookmark_list.html' %}
                                {% endwith %}
                            {% else %}
                            No bookmarks have been added yet.
                            {% endif %}
                    </section> 
                </article>
         {% endblock %}      
    {% block parallax %}
    {% endblock %}